#!/bin/bash
XSOCK=/tmp/.X11-unix
VBUS=/dev/bus/usb
VDRI=/dev/dri

xhost +
docker run --privileged \
	--name="rgbd-scanner" \
	-it \
	--rm \
	-e DISPLAY=$DISPLAY \
	-v $XSOCK:$XSOCK:rw \
	-v $VBUS:$VBUS:rw \
	-v $VDRI:$VDRI:rw \
	rgbdemo/openni:latest
